
# hsv_h: 0.015 # (float) image HSV-Hue augmentation (fraction)
# hsv_s: 0.7 # (float) image HSV-Saturation augmentation (fraction)
# hsv_v: 0.4 # (float) image HSV-Value augmentation (fraction)
# degrees: 0.0 # (float) image rotation (+/- deg)
# translate: 0.1 # (float) image translation (+/- fraction)
# scale: 0.5 # (float) image scale (+/- gain)
# shear: 0.0 # (float) image shear (+/- deg)
# perspective: 0.0 # (float) image perspective (+/- fraction), range 0-0.001
# flipud: 0.0 # (float) image flip up-down (probability)
# fliplr: 0.5 # (float) image flip left-right (probability)
# bgr: 0.0 # (float) image channel BGR (probability)
# mosaic: 1.0 # (float) image mosaic (probability)
# mixup: 0.0 # (float) image mixup (probability)
# copy_paste: 0.0 # (float) segment copy-paste (probability)
# auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
# erasing: 0.4 # (float) probability of random erasing during classification training (0-0.9), 0 means no erasing, must be less than 1.0.
# crop_fraction: 1.0 # (float) image crop fraction for classification (0.1-1), 1.0 means no crop, must be greater than 0.

### Box(P          R      mAP50  mAP50-95):
### 0.992      0.778      0.803      0.503



# hsv_h: 0.3 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.3  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)
# degrees: 40  # image rotation (+/- deg)
# translate: 0.3  # image translation (+/- fraction)
# scale: 0.3  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)
# fliplr: 0.5  # image flip left-right (probability)
# mosaic: 1  # image mosaic (probability)
# mixup: 0.0  # image mixup (probability)

#0.613      0.556      0.644      0.234

# degrees: 45  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)

# hsv_h: 0.3 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.3  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)
# scale: 0.3  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)
# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.987      0.556      0.786      0.354

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)

# hsv_h: 0.3 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.3  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)
# scale: 0.3  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)
# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.854      0.651       0.73      0.508

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)

# hsv_h: 0 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)
# scale: 0.3  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)
# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.999      0.889      0.975      0.562

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)

# hsv_h: 0.5 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.5  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)
# scale: 0.3  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)
# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.942      0.667        0.7      0.432

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0  # image scale (+/- gain)
# shear: 0  # image shear (+/- deg)

# hsv_h: 0.5 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.5  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

#

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0  # image shear (+/- deg)

# hsv_h: 0.5 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.5  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.852      0.642      0.828      0.541

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.5 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.5  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.808      0.556      0.649      0.443

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 1      0.655      0.705      0.425

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.8  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 1      0.838      0.975      0.548

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.968      0.667      0.797      0.568

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.5 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.5  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.5  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.672      0.686       0.75      0.507

# degrees: 45  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.784      0.444      0.491      0.245

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: .7  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 0.968      0.667      0.797      0.568

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.8  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.8  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# # 1      0.537      0.741      0.403

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.7  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# #  0.983      0.667      0.851       0.48

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)
# scale: 0.5  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)

# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# degrees: 0  # image rotation (+/- deg)
# translate: 0.5  # image translation (+/- fraction)
# fliplr: 0.8  # image flip left-right (probability)

# hsv_h: 0 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)
# scale: 0.3  # image scale (+/- gain)
# shear: 0.5  # image shear (+/- deg)
# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)

# 0.999      0.889      0.975      0.562

# -------

# degrees: 15  # image rotation (+/- deg)
# fliplr: 0.8  # image flip left-right (probability)
# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0  # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)
# translate: 0  # image translation (+/- fraction)
# scale: 0  # image scale (+/- gain)
# shear: 0  # image shear (+/- deg)

# 0.626      0.556      0.617       0.36

# degrees: 15  # image rotation (+/- deg)
# fliplr: 0.8  # image flip left-right (probability)
# hsv_h: 0.8 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.8  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.8 # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)
# translate: 0  # image translation (+/- fraction)
# scale: 0  # image scale (+/- gain)
# shear: 0  # image shear (+/- deg)

# # 0.825      0.556      0.509      0.314

# degrees: 15  # image rotation (+/- deg)
# fliplr: 0.8  # image flip left-right (probability)
# hsv_h: 0 # image HSV-Hue augmentation (fraction)
# hsv_s: 0.8  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0 # image HSV-Value augmentation (fraction)

# mosaic: 1  # image mosaic (probability)

# mixup: 0.0  # image mixup (probability)
# perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
# flipud: 0.0  # image flip up-down (probability)
# translate: 0  # image translation (+/- fraction)
# scale: 0  # image scale (+/- gain)
# shear: 0  # image shear (+/- deg)

# # 0.825      0.556      0.509      0.314

hsv_h: 0 # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0 # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0 # (float) image HSV-Value augmentation (fraction)
degrees: 0.0 # (float) image rotation (+/- deg)
translate: 0 # (float) image translation (+/- fraction)
scale: 0 # (float) image scale (+/- gain)
shear: 0.0 # (float) image shear (+/- deg)
perspective: 0.0 # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.0 # (float) image flip up-down (probability)
fliplr: .8 # (float) image flip left-right (probability)
bgr: 0.0 # (float) image channel BGR (probability)
mosaic: 0 # (float) image mosaic (probability)
mixup: 0.0 # (float) image mixup (probability)
copy_paste: 0.0 # (float) segment copy-paste (probability)
auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
erasing: 0 # (float) probability of random erasing during classification training (0-0.9), 0 means no erasing, must be less than 1.0.
crop_fraction: 1 # (float) image crop fraction for classification (0.1-1), 1.0 means no crop, must be greater than 0.

