# augmentations:
hsv_h: 0.3 # image HSV-Hue augmentation (fraction)
hsv_s: 0.3  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.5  # image HSV-Value augmentation (fraction)
degrees: 40  # image rotation (+/- deg)
translate: 0.3  # image translation (+/- fraction)
scale: 0.3  # image scale (+/- gain)
shear: 0.5  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
